### ISSUE TITLE
pvp实现参考

### ISSUE THREAD

**Issue by Steve0x2a** [situ2001/gzhu-jdsd-helper#4]
无意中看到这了，想起之前隐藏起来的代码，重新打开了。
pvp实现的思路可以参考：https://github.com/Steve0x2a/GZHU_JDSD/blob/70860a977fca05d570eb01d308e77843aa5e16f6/fuck_jdsd.py#L91

**Comment by situ2001** [comment]
嗯嗯，但我很好奇这个bug是怎么试出来的🤔

**Comment by Steve0x2a** [comment]
> 嗯嗯，但我很好奇这个bug是怎么试出来的🤔

可以说是巧合了，当时想观察一直轮询的结果 然后他突然加分了。。
