### ISSUE TITLE
貌似现在抓不到key了

### ISSUE THREAD

**Issue by BitSim** [situ2001/gzhu-jdsd-helper#8]
👼 网址变成了http://szextshort.weixin.qq.com/mmtls

不知道是不是这个问题

**求解！！！**

**Comment by situ2001** [comment]
抓取的应该为如下所示的URL的HTTP request body
![image](https://user-images.githubusercontent.com/28241963/202849876-25749f68-7fb8-40ae-a1d5-46203a921730.png)

**Comment by Gomorebug** [comment]
> 抓取的应该为如下所示的URL的HTTP请求正文 ![图像](https://user-images.githubusercontent.com/28241963/202849876-25749f68-7fb8-40ae-a1d5-46203a921730.png)

😭 之前用HTTP debugger可以抓取到URL，但现在不可以了，请问是这个用什么抓取的

**Comment by Gomorebug** [comment]
> 抓取的应该为如下所示的URL的HTTP请求正文 ![图像](https://user-images.githubusercontent.com/28241963/202849876-25749f68-7fb8-40ae-a1d5-46203a921730.png)

😭 之前在电脑用HTTP debugger抓取得到URL，但现在抓取不到了。请问这个是用什么软件抓取得到的

**Comment by BitSim** [comment]
😭 之前在电脑用HTTP debugger抓取得到URL，但现在抓取不到了。请问这个是用什么软件抓取得到的

**Comment by situ2001** [comment]
> > 抓取的应该为如下所示的URL的HTTP请求正文 ![图像](https://user-images.githubusercontent.com/28241963/202849876-25749f68-7fb8-40ae-a1d5-46203a921730.png)
> 
> 
> 
> 😭 之前在电脑用HTTP debugger抓取得到URL，但现在抓取不到了。请问这个是用什么软件抓取得到的

QuantumultX
是个iOS app

**Comment by BitSim** [comment]
> 



> > > 抓取的应该为如下所示的URL的HTTP请求正文 ![图像](https://user-images.githubusercontent.com/28241963/202849876-25749f68-7fb8-40ae-a1d5-46203a921730.png)
> > 
> > 
> > 😭 之前在电脑用HTTP debugger抓取得到URL，但现在抓取不到了。请问这个是用什么软件抓取得到的
> 
> QuantumultX 是个iOS app

**Comment by BitSim** [comment]
> > 
> 
> > > > 抓取的应该为如下所示的URL的HTTP请求正文 ![图像](https://user-images.githubusercontent.com/28241963/202849876-25749f68-7fb8-40ae-a1d5-46203a921730.png)
> > > 
> > > 
> > > 😭 之前在电脑用HTTP debugger抓取得到URL，但现在抓取不到了。请问这个是用什么软件抓取得到的
> > 
> > 
> > QuantumultX 是个iOS app

😭 那请问电脑该怎么抓取

**Comment by situ2001** [comment]
> > > 
> 
> > 
> 
> > > > > 抓取的应该为如下所示的URL的HTTP请求正文 ![图像](https://user-images.githubusercontent.com/28241963/202849876-25749f68-7fb8-40ae-a1d5-46203a921730.png)
> 
> > > > 
> 
> > > > 
> 
> > > > 😭 之前在电脑用HTTP debugger抓取得到URL，但现在抓取不到了。请问这个是用什么软件抓取得到的
> 
> > > 
> 
> > > 
> 
> > > QuantumultX 是个iOS app
> 
> 
> 
> 😭 那请问电脑该怎么抓取

macOS 可以使用 charles

**Comment by BitSim** [comment]
那请问window是不是已经不能抓取了

**Comment by situ2001** [comment]
> 那请问window是不是已经不能抓取了

抱歉，我没用windows好久了……
理论也是可以的

**Comment by BitSim** [comment]
> > 那请问window是不是已经不能抓取了
> 
> 抱歉，我没用Windows好久了......理论也是可以的

🐐 好 谢谢作者大大的回答
